### ISSUE TITLE
Handle directories

### ISSUE THREAD

**Issue by nholden** [nholden/modified-file-filter-action#4]
When a user includes the path to a directory in `args`, if any descendant (of any number of layers) is modified, the action should succeed.

**Comment by gergelyszaz** [comment]
Jordemort has a solution for that (using File::fnmatch), it may be worth looking into it. 
I think it also solves #3, but I only used it with one directory, like `some/dir/*`.
https://github.com/nholden/modified-file-filter-action/compare/master...jordemort:master

**Comment by nholden** [comment]
Definitely open to a PR for this and/or #3! If it helps, I was able to fetch directory names from a file using [`Pathname`](https://ruby-doc.org/stdlib-2.6.3/libdoc/pathname/rdoc/Pathname.html) in another project.

```ruby
require 'Pathname'

Pathname.new("app/models/user.rb").ascend.to_a.map(&:to_s)
=> ["app/models/user.rb", "app/models", "app"]
```

**Comment by gergelyszaz** [comment]
Sure, PR sent: https://github.com/nholden/modified-file-filter-action/pull/11

**Comment by TimmyCarbone** [comment]
Awesome PR, exactly what I need right now!

Any plans of tweaking and merging soon?
I'd have helped but I'm no Ruby dev, sorry :/

**Comment by nholden** [comment]
@TimmyCarbone: Thanks for the ping! I'm excited about that PR, too. There's some feedback that I'd like to get resolved before merging, so I just pinged @gergelyszaz in the PR to check in.

**Comment by nholden** [comment]
Addressed by https://github.com/nholden/modified-file-filter-action/pull/11!
