### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by aaronklaassen** [nholden/modified-file-filter-action#8]
I just noticed this repo doesn't have a `LICENSE` file. If it's intended to be open source, it should be specified as such: https://help.github.com/en/articles/licensing-a-repository

MIT License text, for example, is available here: https://opensource.org/licenses/MIT

Thanks

**Comment by nholden** [comment]
Good catch! Added in https://github.com/nholden/modified-file-filter-action/commit/156112043f30743226f9988e174791d356143d65. Thank you!
